version: '3.4'
services:
  linktree:
    build:
      context: ./
      dockerfile: Dockerfile
    image: devintyler2626/linktree:latest
    ports:
      - '4242:80'
    tty: true
    stdin_open: true
    logging:
      driver: json-file
      options:
        max-size: "10m" 